import content from "../pageBuilder/pages/newsroom/index"

const blogs = [
    {
        index: 1,
        title: "Business Operations during COVID-19 Pandemic",
        description: "The difficult COVID-19 era has also brought out how strong partnerships create lasting value. BG Unified Solutions and Huawei Australia have been working collaboratively to provide all Australians with solid and comprehensive IT solutions....",
        date: "7th September 2020",
        by: "Saurabh Sareen",
        avatar: "/assets/images/team/saurabh.jpg",
        image: "/assets/images/newsroom/businessop.jpg",
        category: "Updates",
        tags: ["Huawei", "virtual desktop" , "bare metal" , "VM" , "VCS" , "free services" , "Remote Phone System" , "Contact Centre", "DC" , "RDSaaS" , "ConstantEFG" , "Uplink" , "E-mail Filtering"],
        link: "1-businessop-during-covid",
        content: content.businessop,
    },
    {
        index: 2,
        title: "Helping Hands during COVID-19 Pandemic",
        description: "COVID-19 working from home taught us more lessons and even let us able to figure it out how we can be exponentially productive than just enjoying the comfort of staying at home....",
        date: "23rd August 2020",
        by: "Saurabh Sareen",
        avatar: "/assets/images/team/saurabh.jpg",
        image: "/assets/images/newsroom/coronavirus.jpg",
        category: "Updates",
        tags: ["B2B" , "VPNHEADEND" , "Firewall" , "10G" , "Paloalto" , "Fortinet" , "ASA" , "UTM" , "ALLFLASH" , "RDSaaS" , "Workstation" , "Cisco", "UCaaS", "Avaya"],
        link: "2-helping-hands-during-covid",
        content: content.covid19,
    },
    {
        index: 3,
        title: "Peace of mind and 60% cost savings with Datacom@AirTrunk",
        description: "It was towards the end of 2019 and the staff at Australian data and applications hosting specialist BG Unified Solutions were looking forward to closing out another busy and successful year....",
        date: "23rd August 2019",
        by: "Saurabh Sareen",
        avatar: "/assets/images/team/saurabh.jpg",
        image: "/assets/images/newsroom/datacom.png",
        category: "Updates",
        tags: ["infrastructure", "iaas", "BGU" , "DDOS" , "SYD1" , "MEL1" , "AirTrunk" , "Datacom", "Saurabh" , "Sareen" , "data hosting" , "infrastructure" , "racks" , "Network"],
        link: "3-collaboration-with-datacom-and-huawei",
        content: content.datacom,
        },
        {
            index: 4,
            title: "A complete Office IT Infrastructure for small to medium size organizations.",
            description: "An enterprise level solution for any small to medium size organization with single or multiple sites. This solution includes:....",
            date: "23rd October 2019",
            by: "Saurabh Sareen",
            avatar: "/assets/images/team/saurabh.jpg",
            image: "/assets/images/newsroom/it-infra.jpg",
            category: "Updates",
            tags: ["cisco", "DID" , "Firewall" , "WLC" , "Apllication Server" , "Backup", "Paloalto", "NOC" , "CPU", "RAM" , "SQL", "Backup", "Storage" , "Warranty"],
            link: "4-Infra-for-medium-businesses",
            content: content.itInfra,
        },
        {
            index: 5,
            title: "Launching a complete VDI/RDS as a Solution",
            description: "We feel proud in announcing ConstantVDI service offering, which will offer you a complete VDI/RDS As A Service Solution using VMWARE, Parallels and Acronis Cyber Infrastructure. ....",
            date: "September 2019",
            by: "Saurabh Sareen",
            avatar: "/assets/images/team/saurabh.jpg",
            image: "/assets/images/newsroom/complete_vdi.jpg",
            category: "Updates",
            tags: ["RDS", "VDI", "POC", "SOE" , "Office 365" , "ConstantVDI" , "VMWARE" , "Acronis" , "Backup", "Microsoft"],
            link: "5-VDI-as-a-Service",
            content: content.vdiaas,
        },
        {
            index: 6,
            title: "Network Infrastructure Redesign",
            description: "The primary purpose of the project is to redesign the network to achieve the following design criteria: ....",
            date: "2019",
            by: "Saurabh Sareen",
            avatar: "/assets/images/team/saurabh.jpg",
            image: "/assets/images/newsroom/it-infra.jpg",
            category: "Case Study",
            tags: ["Network", "Complexity", "Security", "Architecture" , "vendor" , "throughput" , "flexible architecture" , "Cisco IPS" , "Cisco L3", "AIP-SSM"],
            link: "6-Network-Infrastructure-Redesign",
            content: content.networkinfra,
        },
        {
            index: 7,
            title: "Data Center Design and Implementation",
            description: "A client had a requirement to consolidate a distributed environment into a single highly available data centre.....",
            date: "2019",
            by: "Saurabh Sareen",
            avatar: "/assets/images/team/saurabh.jpg",
            image: "/assets/images/newsroom/infra_redesign.jpg",
            category: "Case Study",
            tags: ["dispersed sites", "infrastructure", "dual-site", "dual-core" , "network topology" , "Enterprsie" , "Storage Assesment" , "data center" , "Palo Alto", "Huawei 10G"],
            link: "7-Data-Center-Design-and-Implementation",
            content: content.dcdesign,
        },
        {
            index: 8,
            title: "BG Unified Solutions Hosted UC Solution",
            description: "Currently hosted in NEXTDC, consisting of 18 UCS Server, C Series & B Series in the farm. Each UCS Server is running ESX version 5.5 with updated VMWARE tools. .....",
            date: "2019",
            by: "Saurabh Sareen",
            avatar: "/assets/images/team/saurabh.jpg",
            image: "/assets/images/services/infra.jpg",
            category: "Case Study",
            tags: ["Nimble", "WLC", "Nexus", "SourceFire" , "Cisco ASA" , "DC" , "VMWARE" , "ESX" , "UCS", "NEXTDC", "NetApp" , "SPLUNK" , "CUBE" , "SRST" , "UC"],
            link: "8-BG-Unified-Solutions-Hosted-UC-Solution",
            content: content.hosteduc,
        },
        {
            index: 9,
            title: "F5 Topology Redesign",
            description: "F5 Configuration was redesigned and implemented in a recommended way. A lot of IRULES/POOLS defined to achieve the desired configuration requirements. Health Monitors were rewritten to provide the best monitor for the servers in different pools......",
            date: "2019",
            by: "Saurabh Sareen",
            avatar: "/assets/images/team/saurabh.jpg",
            image: "/assets/images/newsroom/f5_redesign.jpg",
            category: "Case Study",
            tags: ["ASM" , "PCI", "iApps", "TOMCAT", "IPs" , "POOLS" , "IRULES" , "Load Balancer" , "F5" , "routers", "WAN"],
            link: "9-F5-Topology-Redesign",
            content: content.f5top,
        }
        
    ]
    
    
    


export default blogs