export default [
    {
        id: 1,
        imageUrl: "/assets/images/brands/cisco.png",
        imageAlt: "Company Logo",
        author: "Dave Moy",
        paragraph: "BG Solutions has gained an excellent reputation in design and implementation of IP telephony networks and significant experience in Cisco Contact center design and implementation.",
        description: "BG Solutions has gained an excellent reputation in design and implementation of IP telephony networks and significant experience in Cisco Contact center design and implementation for a number of call centers and distributed call center environments. Saurabh and his team have a strong background in Unity Design and Implementation and Cisco Unified Presence",
        CompanyName: "Cisco Business Development Manager Dicker Data",
    },
    {
        id: 2,
        imageUrl: "assets/images/brands/optus.png",
        imageAlt: "Company Logo",
        author: "Tushar Bhatt",
        paragraph: "Their experts in different technologies like security, voice and a broad range of skills including F5, WAN Optimizatin, WAN... have proven to be quite valuable to us.",
        description: "Their experts in different technologies like security, voice and a broad range of skills including F5 Load balancers, WAN Optimizatin, WAN , Cloud technologies and Cisco technologies have proven to be quite valuable to us. This has created high business efficiency for Optus, especially for voice/ video projects, WAN implementation, DC design. ",
        CompanyName: "Senior Network Engineer, OPTUS",
    },

    {
        id: 3,
        imageUrl: "assets/images/brands/ambition_tech.png",
        imageAlt: "Company Logo",
        author: "Kelly McCaughey",
        paragraph: "I have worked with BG Unified Solutions for approximately 1 year now. I have found BG Unified Solutions to be a highly reputable company with a work ethic and reliability that is second to none. ",
        description: "I have worked with BG Unified Solutions for approximately 1 year now. I have found BG Unified Solutions to be a highly reputable company with a work ethic and reliability that is second to none. I would highly recommend BG Unified Solutions to any client, and indeed have introduced them to a number of Ambition’s clients in recent times.",
        CompanyName: "Infrastructure Consultant, Ambition Technology",
    },
    {
        id: 4,
        imageUrl: "assets/images/brands/nsw_gov.png",
        imageAlt: "Company Logo",
        author: "Kate Romanenko",
        paragraph: "I worked with BGUS during his time at Revenue NSW (OSR). They undertook a massive task of F5 load balancer upgrade - and things like that never go smoothly.",
        description: "I worked with BGUS during his time at Revenue NSW (OSR). They undertook a massive task of F5 load balancer upgrade - and things like that never go smoothly. What was absolutely amazing is the speed with which they resolved every single issue we encountered after.",
        CompanyName: "Senior Application Developer at Revenue NSW",
    },
    {
        id: 5,
        imageUrl: "assets/images/brands/Rackspace_Technology.png",
        imageAlt: "Company Logo",
        author: "Bryan Cawse",
        paragraph: "I have had the opportunity to have worked with BGUS with multiple vendors. They have a brilliant customer orientated demeanor and their technical skills are second to none. ",
        description: "I had the opportunity to have worked with BGUS with multiple vendors. They have a brilliant customer orientated demeanor and their technical skills are second to none. When it comes to Information Security I can always rely on BGUS to connect the technical elements to that of the customer's needs.",
        CompanyName: "Senior Enterprise Account Executive at Rackspace Technology",
    },
    {
        id: 6,
        imageUrl: "assets/images/brands/sabre_pacific.png",
        imageAlt: "Company Logo",
        author: "Munish Verma",
        description: "BG Unified Solutions worked together with our in-house engineers, whom we engaged to redesign our network. Saurabh was the engineer in-charge, who designed the whole solution to reduce the overall complexity and remove bottlenecks. They worked cohesively with our in-house team and brought great technical skills & expertise on Cisco switches, routers, firewalls, content switches, IPS etc. Throughout the project, their dedication was remarkable. They ensured that project is completed with minimum end-user impact and since all the implementations were performed in middle of night, they made themselves personally available for mid-night implementations and any post-implementation support. Would highly recommend their skills, expertise and professional services.",
        CompanyName: "Head of Technology Services at Sabre Pacific Pty Ltd",
    },
    {
        id: 7,
        imageUrl: "assets/images/brands/telstra.png",
        imageAlt: "Company Logo",
        description: "Saurabh(Sunny) from BG Unified Solutions, is the ultimate technical engineer with an attitude that ‘nothing is too hard’ with a focus that ‘an affordable high quality solution will be found’. Sunny’s personal disposition is a true reflection of his nick name and he is an absolute delight to work with. He never stops seeking improvement, in both himself and in delivery of solutions. He is a highly regarded.",
        CompanyName: "Senior Sales Executive at Cloud Computing Telstra",
    },
    {
        id: 8,
        imageUrl: "assets/images/brands/nsw_gov.png",
        author: "Jeremy Wood",
        imageAlt: "Company Logo",
        description: <span>BG Unified Solutions came on board for a Contact Center consolidation project. They are leading the architect team to consolidate 180 Contact Centers of Service NSW. We found their skills are far more advanced and trustworthy than any of the technology vendors we have. As a result, now BGUS is covering more widened scope of work that initially allocated. They have gained an excellent reputation in the whole organization especially in the design and implementation of IP telephony networks. They have significant experience in Cisco Contact Centre design and implementation for a number of call centres and distributed call centre environments.
        Saurabh and his team have a strong background in multiple technologies. They also have experience in implementing CUBE - Flow-through / Flow-around / Hybrid Models and fixed the critical issues most of the times. I would highly recommend them. Feel free to contact me for any further clarification.
        </span>,
        CompanyName: "Project Manager at Service NSW, NSW Government",
    },
    {
        id: 9,
        imageUrl: "assets/images/brands/datacom.png",
        author: "Bruce McEwen",
        imageAlt: "Company Logo",
        paragraph: "Sunny has a passion for customer delivery and the management of risk out of the supply chain that supports him. That’s one of the ingredients for success.",
        description: <span>Sunny has a passion for customer delivery and the management of risk out of the supply chain that supports him. If providers of services to BG Solutions let them down or do not enhance and improve the quality of BG solutions customer experiences he is prepared to look elsewhere. That’s one of the ingredients for success.</span>,
        CompanyName: "Associate Director at Datacom",
    },
    {
        id: 10,
        author: "Houman Asefi",
        imageAlt: "Company Logo",
        description: <span>Saurabh (Sunny) is a rare combination of technical mastery and entrepreneurship mindset with the mojo of "getting things done fast". He has the capacity of an engineering business unit and step up to help whenever he can. His customers can testify on his unique work and are proof of his dedication and hard work. Plus, he is a great humble friend of mine. Wish you all the best Sunny.</span>,
        CompanyName: "Sales Strategy Executive, Let’s SaaS",
    },

]